### ISSUE TITLE
Command parameters can be anything.

### ISSUE THREAD

**Issue by sehraf** [filips123/ZeroFramePy#3]
Line [424](https://github.com/filips123/ZeroFramePy/blob/master/zeroframe_ws_client/__init__.py#L424) suggests that params should be a dictionary, but looking at what zite send though the websocket the data can be anything:
```json
{"cmd":"mergerSiteList","params":true,"wrapper_nonce":"6...d","id":310}
{"cmd":"dbQuery","params":["SELECT site, COUNT(site) as count FROM json GROUP BY site"],"wrapper_nonce":"6...d","id":311}
{"cmd":"optionalHelpList","params":"1...r","wrapper_nonce":"4...c","id":314}
```
Same goes for `cmdp`.

This also seems to be  an issue with the ZeroFrame API Reference!
Following it results in an error:
Calling [optionalHelpList](https://zeronet.io/docs/site_development/zeroframe_api_reference/#optionalhelplist) with `params: {"address": "something"}` results in this:
`[ZeroFrame] Unknown request {'cmd': 'error', 'params': 'Internal error: AttributeError("\'list\' object has no attribute \'startswith\'"): \'list\' object has no attribute \'startswith\'<br><small class=\'multiline\'>UiWebsocket.py line 189 > MergerSite/MergerSitePlugin.py line 153 > 135</small>', 'id': 3}` 
While omitting `address` and just sending `params: "something"` works fine.

**Comment by filips123** [comment]
Sorry for delay, this is now fixed. Docs now say that `params` can be any type.
